---
apiVersion: v1
kind: Service
metadata:
  name: eventsource
  labels:
    app: eventsource
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  eventsource-mapping
      prefix: /backend/eventsource
      service: eventsource:8081
spec:
  type: NodePort
  selector:
    app: eventsource
  ports:
    - protocol: TCP
      port: 8081
      name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: eventsource
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eventsource
    spec:
      containers:
        - name: eventsource
          image: rchiarinelli/eventsource:0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
